project:
  type: website
  output-dir: docs

website:
  title: "Maisha Tasneem"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: scorecard_analysis.qmd
        text: Project 1
      - href: fec-analysis.qmd
        text: Project 2
      - href: mapping.qmd
        text: Project 3
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

